---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orders
data:
  RETAIL_ORDERS_MESSAGING_PROVIDER: rabbitmq
  RETAIL_ORDERS_MESSAGING_RABBITMQ_ADDRESSES: orders-rabbitmq:5672
  RETAIL_ORDERS_PERSISTENCE_PROVIDER: postgres
  RETAIL_ORDERS_PERSISTENCE_ENDPOINT: orders-postgresql:5432
  RETAIL_ORDERS_PERSISTENCE_NAME: orders
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-order
  namespace: default
  labels:
    app: retail-order
spec:
  selector:
    matchLabels:
      app: retail-order
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: retail-order
    spec:
      containers:
        - name: retail-order
          image: "public.ecr.aws/aws-containers/retail-store-sample-orders:1.6.1"
          imagePullPolicy: IfNotPresent
          restartPolicy: Always
          fsGroup: 1000
          ports:
            - containerPort: 8080
              name: retail-order
          volumeMounts:
            - name: temp-volume
              mountPath: /tmp
          resources:
            requests:
              cpu: 256m
              memory: 512Mi
            limits:
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            env:
              - name: JAVA_OPTS
                value: -XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
          envFrom:
            - configMapKeyRef:
                name: orders
            - secretRef:
                name: rds-cred
            - secretRef:
                name: rabbitmq-config
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: retail-order-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: retail-order
  ports:
    - name: retail-order-service
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30040
