---
- name: Configure Kubernetes Cluster (Worker Node)
  hosts: _worker
  vars_files:
    - ./varfile.yml
  tasks:
    - name: Reset Kubeadm to Reset IP on Image
      ansible.builtin.command:
        cmd: kubeadm reset -f
      become: true

    - name: Read join command from local file
      set_fact:
        join_command: "{{ lookup('file', './k8s_join_command.txt') }}"

    - name: Join the worker to the cluster
      ansible.builtin.command: "{{ join_command }}"
      register: join_result
      become: true

    # - name: Change Node Label
    #   ansible.builtin.shell: kubectl label node $(hostname) node-role.kubernetes.io/worker=