---
- name: Configure Kubernetes Cluster (Worker Node)
  hosts: _worker
  vars_files:
    - ./varfile.yml
  tasks:
    - name: Reset Kubeadm to Reset IP on Image
      ansible.builtin.command:
        cmd: kubeadm reset -f
      become: true

    - name: Read join command from local file
      set_fact:
        join_command: "{{ lookup('file', './k8s_join_command.txt') }}"

    - name: Join the worker to the cluster
      ansible.builtin.command: "{{ join_command }}"
      register: join_result
      become: true

    - name: Delete .kube Directory
      ansible.builtin.command:
        cmd: rm -rf ~/.kube

    - name: Make New .kube Directory
      ansible.builtin.command:
        cmd: mkdir -p $HOME/.kube

    - name: Upload .kube config File
      ansible.builtin.copy:
        src: ./k8s.config
        dest: $HOME/.kube/config

    - name: Change Node Label
      ansible.builtin.shell: kubectl label node $(hostname) node-role.kubernetes.io/worker=

    - name: Apply Networking CNI Plugin
      ansible.builtin.shell: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
      ignore_errors: true
      become: true

