#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

# Configuration Variables
KUBERNETES_VERSION="v1.36" # Adjust version as needed (e.g., v1.29, v1.30)
POD_CIDR="10.244.0.0/16"   # Standard CIDR for Flannel CNI

# Colors for output
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== Starting Kubernetes Node Provisioning ===${NC}"

# 1. Disable Swap (Required by Kubernetes)
echo -e "${GREEN}[1/6] Disabling Swap...${NC}"
sudo swapoff -a
sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

# 2. Set up IPv4 forwarding and let iptables see bridged traffic
echo -e "${GREEN}[2/6] Configuring sysctl and kernel modules...${NC}"
cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
overlay
br_netfilter
EOF

sudo modprobe overlay
sudo modprobe br_netfilter

cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-iptables  = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward                 = 1
EOF

sudo sysctl --system

# 3. Install containerd Container Runtime
echo -e "${GREEN}[3/6] Installing containerd...${NC}"
sudo apt-get update -y
sudo apt-get install -y curl gnupg2 software-properties-common apt-transport-https ca-certificates

sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt-get update -y
sudo apt-get install -y containerd.io

# Configure containerd to use systemd cgroup driver (Critical for K8s stability)
sudo mkdir -p /etc/containerd
containerd config default | sudo tee /etc/containerd/config.toml >/dev/null
sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
sudo systemctl restart containerd
sudo systemctl enable containerd

# 4. Install kubelet, kubeadm, and kubectl
echo -e "${GREEN}[4/6] Installing Kubernetes packages ($KUBERNETES_VERSION)...${NC}"
curl -fsSL https://pkgs.k8s.io/core:/stable:/${KUBERNETES_VERSION}/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/${KUBERNETES_VERSION}/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list

sudo apt-get update -y
sudo apt-get install -y kubelet kubeadm kubectl
sudo apt-mark hold kubelet kubeadm kubectl

# 5. Determine Node Role and Initialize/Configure
echo -e "${GREEN}[5/6] Detecting Node Role...${NC}"

# Check if script argument is passed ("master" or "worker"), otherwise guess by hostname
# ROLE="master"
if [ -z "$ROLE" ]; then
    if [[ "$(hostname)" =~ "master" ]]; then
        ROLE="master"
    else
        ROLE="worker"
    fi
fi

if [ "$ROLE" == "master" ]; then
    echo -e "${GREEN}==> Initializing Control Plane (Master Node)...${NC}"
    
    # Initialize the cluster
    sudo kubeadm init --pod-network-cidr=$POD_CIDR

    # Configure kubectl for the current admin user
    echo -e "${GREEN}[6/6] Configuring kubectl local context...${NC}"
    mkdir -p $HOME/.kube
    sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config

    # Install Flannel Network Plugin (CNI)
    echo -e "${GREEN}==> Deploying Flannel CNI network...${NC}"
    kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml

    echo -e "\n${GREEN}=== Master Node Setup Complete! ===${NC}"
    echo "To allow worker nodes to join, copy the 'kubeadm join' command printed above and run it on your worker nodes."
    echo "Check cluster status with: kubectl get nodes"

else
    echo -e "${GREEN}==> Worker Node Environment Ready!${NC}"
    echo -e "${GREEN}[6/6] Awaiting cluster join...${NC}"
    echo "Please run the 'kubeadm join' token command generated by your Master node to join this worker to the cluster."
fi