---
plugin: amazon.aws.aws_ec2
profile: kareem-aziz
regions:
  - us-east-1

filters:
  instance-state-name: running
  tag:Env:
    - k8s

hostnames:
  - instance-id

keyed_groups:
  - key: tags.Env

compose:
  # Links your custom ssh.config file to every discovered host
  ansible_ssh_common_args: "'-F ./ssh.config'"

  # Sets the default connection user (e.g., ec2-user, ubuntu, admin)
  ansible_user: "'ubuntu'"
